#%RAML 1.0 Library
uses:
  group: group.raml
  pragma: pragma.raml
  deploymentSteps: deploymentSteps.raml

types:
  DeploymentPlan:
    type: object
    (pragma.serializeOnly): # Used only for serialization
    description: |
       A deployment is a change in the service setup.
    properties:
      id:
        type: string
        description: The UUID of the deployment plan
      steps:
        type: deploymentSteps.DeploymentSteps
        description: The total number of steps to be performed in the deployment
      version:
        type: datetime
        description: The time when the deployment was created, used as deployment version
