
get:
  description:
    List all running deployments.
    A deployment is a change in the service setup.

    A deployment is identified by an id, affects a set of applications and is composed of deployment steps.

    Every step contains a list of actions with following types

    * <code>StartApplication</code> starts an application, which is currently not running.

    * <code>StopApplication</code> stops an already running application.

    * <code>ScaleApplication</code> changes the number of instances of an application and allows to kill specified instances while scaling.

    * <code>RestartApplication</code> upgrades an already deployed application with a new version.

    * <code>ResolveArtifacts</code> Resolve all artifacts of an application

  is: [ secured ]
  responses:
    200:
      description: "The list of all running deployments."
      body:
        application/json:
          example: !include examples/deployments.json


/{deployment_id}:
  delete:
    description: Revert the deployment with `deployment_id` by creating a new deployment which reverses
                 all changes.
    is: [ secured ]
    queryParameters:
      force:
        description: If set to <code>false</code> (the default) then the deployment is
                canceled and a new deployment is created to revert the changes of this
                deployment. Without concurrent deployments, this restores the configuration before this
                deployment. If set to <code>true</code>, then the deployment
                is still canceled but no rollback deployment is created.
        type: boolean
        default: false
    responses:
      200:
        description:
          A deployment is started which has a unique deployment identifier.
          The related deployment can be fetched from the /v2/deployments endpoint.
          If the deployement is gone from the list of deployments, it means that it is finished.
          As long as the deployment runs, the effect of that change operation is visible only partially.
        body:
          application/json:
            example: !include examples/deployments_result.json
      202:
        description:
          If the force flag is set to true, the deployment is canceled and no new deployment is triggered.
          In this case no body is returned.
      404:
        description: "The deployment plan with the given id can not be found."
        body:
          application/json:
            example: |
              { "message": "DeploymentPlan unknown_deployment does not exist" }


