FROM mesosphere/mesos:0.22.1-1.0.ubuntu1404

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install --no-install-recommends -y \
    default-jdk \
    curl

RUN curl -SsL -O http://dl.bintray.com/sbt/debian/sbt-0.13.5.deb && \
    dpkg -i sbt-0.13.5.deb

COPY . /marathon
WORKDIR /marathon
