#!/bin/bash

# Version script for Marathon.
#
# Change MINOR to x+1 and BRANCH_POINT to commit hash of common ancestor of master and releases/1.x
# after a releases/1.x was cut
MAJOR=1
MINOR=9
BRANCH_POINT=8228cea
REF=HEAD

declare -a OTHERARGS
help() {
  cat <<-EOF
Usage $0 [options]

  --help This help
  --ref  The reference for which version to output Defaults to HEAD

Non-arg params

- commit: output just the formatted commit hash
- docker: output the version as used by the Docker tag
EOF
}

while ! [ -z "$1" ]; do
  arg="$1"
  shift
  case "$arg" in
    --help)
      help
      exit 0
      ;;
    --ref)
      REF="$1"
      shift
      ;;
    *)
      OTHERARGS+=("$arg")
      ;;
  esac
done

# Infer version
# Number of commits since branch point
COMMIT_NUMBER="$(git rev-list --count --first-parent $BRANCH_POINT..$REF)"
COMMIT_HASH=$(git rev-parse --short $REF)

# Echo commit hash
if [ "${OTHERARGS[0]}" == "commit" ]; then
    echo "$COMMIT_HASH"
    exit 0
fi

# Version for Docker image, e.g. v1.7.42
if [ "${OTHERARGS[0]}" == "docker" ]; then
    echo "v$MAJOR.$MINOR.$COMMIT_NUMBER"
    exit 0
fi

# Echo verion
# E.g. 1.7.42
echo "$MAJOR.$MINOR.$COMMIT_NUMBER"
