#!/bin/bash

MAJOR=1
MINOR=6
BRANCH_POINT=aa89e89

# Infer version
# Number of commits since branch point
BUILD_NUMBER="$(git rev-list --count --first-parent $BRANCH_POINT..HEAD)"
COMMIT_HASH="$(git rev-parse --short HEAD)"

# E.g. 1.7.42-deadbeef
echo "$MAJOR.$MINOR.$BUILD_NUMBER-$COMMIT_HASH"
