#!/bin/sh
set -e

codename () {
  out $(lsb_release -cs)
}

out () { printf '%s\n' "$*" ;}

case "$1" in
  purge)
    if [ "$(codename)" = "wheezy" ]; then
      # Disable the SYSV links (only used on select systems).
      update-rc.d marathon remove
    fi
    ;;

  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
