
get:
  description: Get info about the Marathon Instance
  responses:
    200:
      description: General configuration and runtime information about this Marathon instance.
      body:
        application/json:
          example: !include examples/info.json
