#%RAML 1.0
title: v2 pod API
mediaType: application/json
types:
  Pod: !include types/pod.raml
  PathId: !include types/pathId.raml
/{id}:
  uriParameters:
    id:
      type: PathId
      description: The path of the pod
  # TODO: traits.raml needs to be updated... is: [ secured ]
  get:
    description:
      Get the pod at the given id
    responses:
      200:
        body:
          application/json:
            type: Pod
      404:
        description: No pod found with this `id`
