// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: marathon.proto

package mesosphere.marathon;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServiceDefinitionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required .mesos.CommandInfo cmd = 2;
    boolean hasCmd();
    org.apache.mesos.Protos.CommandInfo getCmd();
    org.apache.mesos.Protos.CommandInfoOrBuilder getCmdOrBuilder();
    
    // required uint32 instances = 3;
    boolean hasInstances();
    int getInstances();
    
    // repeated .mesos.Resource resources = 4;
    java.util.List<org.apache.mesos.Protos.Resource> 
        getResourcesList();
    org.apache.mesos.Protos.Resource getResources(int index);
    int getResourcesCount();
    java.util.List<? extends org.apache.mesos.Protos.ResourceOrBuilder> 
        getResourcesOrBuilderList();
    org.apache.mesos.Protos.ResourceOrBuilder getResourcesOrBuilder(
        int index);
    
    // optional string description = 5;
    boolean hasDescription();
    String getDescription();
    
    // optional uint32 port = 6;
    boolean hasPort();
    int getPort();
    
    // optional double rackAffinity = 7;
    boolean hasRackAffinity();
    double getRackAffinity();
    
    // optional double nodeAffinity = 8;
    boolean hasNodeAffinity();
    double getNodeAffinity();
  }
  public static final class ServiceDefinition extends
      com.google.protobuf.GeneratedMessage
      implements ServiceDefinitionOrBuilder {
    // Use ServiceDefinition.newBuilder() to construct.
    private ServiceDefinition(Builder builder) {
      super(builder);
    }
    private ServiceDefinition(boolean noInit) {}
    
    private static final ServiceDefinition defaultInstance;
    public static ServiceDefinition getDefaultInstance() {
      return defaultInstance;
    }
    
    public ServiceDefinition getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mesosphere.marathon.Protos.internal_static_mesosphere_marathon_ServiceDefinition_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mesosphere.marathon.Protos.internal_static_mesosphere_marathon_ServiceDefinition_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .mesos.CommandInfo cmd = 2;
    public static final int CMD_FIELD_NUMBER = 2;
    private org.apache.mesos.Protos.CommandInfo cmd_;
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.apache.mesos.Protos.CommandInfo getCmd() {
      return cmd_;
    }
    public org.apache.mesos.Protos.CommandInfoOrBuilder getCmdOrBuilder() {
      return cmd_;
    }
    
    // required uint32 instances = 3;
    public static final int INSTANCES_FIELD_NUMBER = 3;
    private int instances_;
    public boolean hasInstances() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getInstances() {
      return instances_;
    }
    
    // repeated .mesos.Resource resources = 4;
    public static final int RESOURCES_FIELD_NUMBER = 4;
    private java.util.List<org.apache.mesos.Protos.Resource> resources_;
    public java.util.List<org.apache.mesos.Protos.Resource> getResourcesList() {
      return resources_;
    }
    public java.util.List<? extends org.apache.mesos.Protos.ResourceOrBuilder> 
        getResourcesOrBuilderList() {
      return resources_;
    }
    public int getResourcesCount() {
      return resources_.size();
    }
    public org.apache.mesos.Protos.Resource getResources(int index) {
      return resources_.get(index);
    }
    public org.apache.mesos.Protos.ResourceOrBuilder getResourcesOrBuilder(
        int index) {
      return resources_.get(index);
    }
    
    // optional string description = 5;
    public static final int DESCRIPTION_FIELD_NUMBER = 5;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional uint32 port = 6;
    public static final int PORT_FIELD_NUMBER = 6;
    private int port_;
    public boolean hasPort() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getPort() {
      return port_;
    }
    
    // optional double rackAffinity = 7;
    public static final int RACKAFFINITY_FIELD_NUMBER = 7;
    private double rackAffinity_;
    public boolean hasRackAffinity() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public double getRackAffinity() {
      return rackAffinity_;
    }
    
    // optional double nodeAffinity = 8;
    public static final int NODEAFFINITY_FIELD_NUMBER = 8;
    private double nodeAffinity_;
    public boolean hasNodeAffinity() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public double getNodeAffinity() {
      return nodeAffinity_;
    }
    
    private void initFields() {
      id_ = "";
      cmd_ = org.apache.mesos.Protos.CommandInfo.getDefaultInstance();
      instances_ = 0;
      resources_ = java.util.Collections.emptyList();
      description_ = "";
      port_ = 0;
      rackAffinity_ = 0D;
      nodeAffinity_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInstances()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCmd().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getResourcesCount(); i++) {
        if (!getResources(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, cmd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, instances_);
      }
      for (int i = 0; i < resources_.size(); i++) {
        output.writeMessage(4, resources_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(6, port_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(7, rackAffinity_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(8, nodeAffinity_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, cmd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, instances_);
      }
      for (int i = 0; i < resources_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, resources_.get(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, port_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, rackAffinity_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, nodeAffinity_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static mesosphere.marathon.Protos.ServiceDefinition parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static mesosphere.marathon.Protos.ServiceDefinition parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static mesosphere.marathon.Protos.ServiceDefinition parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static mesosphere.marathon.Protos.ServiceDefinition parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static mesosphere.marathon.Protos.ServiceDefinition parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static mesosphere.marathon.Protos.ServiceDefinition parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static mesosphere.marathon.Protos.ServiceDefinition parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static mesosphere.marathon.Protos.ServiceDefinition parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static mesosphere.marathon.Protos.ServiceDefinition parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static mesosphere.marathon.Protos.ServiceDefinition parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(mesosphere.marathon.Protos.ServiceDefinition prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements mesosphere.marathon.Protos.ServiceDefinitionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mesosphere.marathon.Protos.internal_static_mesosphere_marathon_ServiceDefinition_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mesosphere.marathon.Protos.internal_static_mesosphere_marathon_ServiceDefinition_fieldAccessorTable;
      }
      
      // Construct using mesosphere.marathon.Protos.ServiceDefinition.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCmdFieldBuilder();
          getResourcesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (cmdBuilder_ == null) {
          cmd_ = org.apache.mesos.Protos.CommandInfo.getDefaultInstance();
        } else {
          cmdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        instances_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (resourcesBuilder_ == null) {
          resources_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          resourcesBuilder_.clear();
        }
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        rackAffinity_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        nodeAffinity_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mesosphere.marathon.Protos.ServiceDefinition.getDescriptor();
      }
      
      public mesosphere.marathon.Protos.ServiceDefinition getDefaultInstanceForType() {
        return mesosphere.marathon.Protos.ServiceDefinition.getDefaultInstance();
      }
      
      public mesosphere.marathon.Protos.ServiceDefinition build() {
        mesosphere.marathon.Protos.ServiceDefinition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private mesosphere.marathon.Protos.ServiceDefinition buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        mesosphere.marathon.Protos.ServiceDefinition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public mesosphere.marathon.Protos.ServiceDefinition buildPartial() {
        mesosphere.marathon.Protos.ServiceDefinition result = new mesosphere.marathon.Protos.ServiceDefinition(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (cmdBuilder_ == null) {
          result.cmd_ = cmd_;
        } else {
          result.cmd_ = cmdBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.instances_ = instances_;
        if (resourcesBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            resources_ = java.util.Collections.unmodifiableList(resources_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.resources_ = resources_;
        } else {
          result.resources_ = resourcesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.rackAffinity_ = rackAffinity_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.nodeAffinity_ = nodeAffinity_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mesosphere.marathon.Protos.ServiceDefinition) {
          return mergeFrom((mesosphere.marathon.Protos.ServiceDefinition)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(mesosphere.marathon.Protos.ServiceDefinition other) {
        if (other == mesosphere.marathon.Protos.ServiceDefinition.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasCmd()) {
          mergeCmd(other.getCmd());
        }
        if (other.hasInstances()) {
          setInstances(other.getInstances());
        }
        if (resourcesBuilder_ == null) {
          if (!other.resources_.isEmpty()) {
            if (resources_.isEmpty()) {
              resources_ = other.resources_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureResourcesIsMutable();
              resources_.addAll(other.resources_);
            }
            onChanged();
          }
        } else {
          if (!other.resources_.isEmpty()) {
            if (resourcesBuilder_.isEmpty()) {
              resourcesBuilder_.dispose();
              resourcesBuilder_ = null;
              resources_ = other.resources_;
              bitField0_ = (bitField0_ & ~0x00000008);
              resourcesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getResourcesFieldBuilder() : null;
            } else {
              resourcesBuilder_.addAllMessages(other.resources_);
            }
          }
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasRackAffinity()) {
          setRackAffinity(other.getRackAffinity());
        }
        if (other.hasNodeAffinity()) {
          setNodeAffinity(other.getNodeAffinity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasCmd()) {
          
          return false;
        }
        if (!hasInstances()) {
          
          return false;
        }
        if (!getCmd().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getResourcesCount(); i++) {
          if (!getResources(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              org.apache.mesos.Protos.CommandInfo.Builder subBuilder = org.apache.mesos.Protos.CommandInfo.newBuilder();
              if (hasCmd()) {
                subBuilder.mergeFrom(getCmd());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCmd(subBuilder.buildPartial());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              instances_ = input.readUInt32();
              break;
            }
            case 34: {
              org.apache.mesos.Protos.Resource.Builder subBuilder = org.apache.mesos.Protos.Resource.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addResources(subBuilder.buildPartial());
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              description_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              port_ = input.readUInt32();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              rackAffinity_ = input.readDouble();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              nodeAffinity_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required .mesos.CommandInfo cmd = 2;
      private org.apache.mesos.Protos.CommandInfo cmd_ = org.apache.mesos.Protos.CommandInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.apache.mesos.Protos.CommandInfo, org.apache.mesos.Protos.CommandInfo.Builder, org.apache.mesos.Protos.CommandInfoOrBuilder> cmdBuilder_;
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.apache.mesos.Protos.CommandInfo getCmd() {
        if (cmdBuilder_ == null) {
          return cmd_;
        } else {
          return cmdBuilder_.getMessage();
        }
      }
      public Builder setCmd(org.apache.mesos.Protos.CommandInfo value) {
        if (cmdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cmd_ = value;
          onChanged();
        } else {
          cmdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setCmd(
          org.apache.mesos.Protos.CommandInfo.Builder builderForValue) {
        if (cmdBuilder_ == null) {
          cmd_ = builderForValue.build();
          onChanged();
        } else {
          cmdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeCmd(org.apache.mesos.Protos.CommandInfo value) {
        if (cmdBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              cmd_ != org.apache.mesos.Protos.CommandInfo.getDefaultInstance()) {
            cmd_ =
              org.apache.mesos.Protos.CommandInfo.newBuilder(cmd_).mergeFrom(value).buildPartial();
          } else {
            cmd_ = value;
          }
          onChanged();
        } else {
          cmdBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearCmd() {
        if (cmdBuilder_ == null) {
          cmd_ = org.apache.mesos.Protos.CommandInfo.getDefaultInstance();
          onChanged();
        } else {
          cmdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public org.apache.mesos.Protos.CommandInfo.Builder getCmdBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCmdFieldBuilder().getBuilder();
      }
      public org.apache.mesos.Protos.CommandInfoOrBuilder getCmdOrBuilder() {
        if (cmdBuilder_ != null) {
          return cmdBuilder_.getMessageOrBuilder();
        } else {
          return cmd_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.apache.mesos.Protos.CommandInfo, org.apache.mesos.Protos.CommandInfo.Builder, org.apache.mesos.Protos.CommandInfoOrBuilder> 
          getCmdFieldBuilder() {
        if (cmdBuilder_ == null) {
          cmdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.apache.mesos.Protos.CommandInfo, org.apache.mesos.Protos.CommandInfo.Builder, org.apache.mesos.Protos.CommandInfoOrBuilder>(
                  cmd_,
                  getParentForChildren(),
                  isClean());
          cmd_ = null;
        }
        return cmdBuilder_;
      }
      
      // required uint32 instances = 3;
      private int instances_ ;
      public boolean hasInstances() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getInstances() {
        return instances_;
      }
      public Builder setInstances(int value) {
        bitField0_ |= 0x00000004;
        instances_ = value;
        onChanged();
        return this;
      }
      public Builder clearInstances() {
        bitField0_ = (bitField0_ & ~0x00000004);
        instances_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .mesos.Resource resources = 4;
      private java.util.List<org.apache.mesos.Protos.Resource> resources_ =
        java.util.Collections.emptyList();
      private void ensureResourcesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          resources_ = new java.util.ArrayList<org.apache.mesos.Protos.Resource>(resources_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.mesos.Protos.Resource, org.apache.mesos.Protos.Resource.Builder, org.apache.mesos.Protos.ResourceOrBuilder> resourcesBuilder_;
      
      public java.util.List<org.apache.mesos.Protos.Resource> getResourcesList() {
        if (resourcesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(resources_);
        } else {
          return resourcesBuilder_.getMessageList();
        }
      }
      public int getResourcesCount() {
        if (resourcesBuilder_ == null) {
          return resources_.size();
        } else {
          return resourcesBuilder_.getCount();
        }
      }
      public org.apache.mesos.Protos.Resource getResources(int index) {
        if (resourcesBuilder_ == null) {
          return resources_.get(index);
        } else {
          return resourcesBuilder_.getMessage(index);
        }
      }
      public Builder setResources(
          int index, org.apache.mesos.Protos.Resource value) {
        if (resourcesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResourcesIsMutable();
          resources_.set(index, value);
          onChanged();
        } else {
          resourcesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setResources(
          int index, org.apache.mesos.Protos.Resource.Builder builderForValue) {
        if (resourcesBuilder_ == null) {
          ensureResourcesIsMutable();
          resources_.set(index, builderForValue.build());
          onChanged();
        } else {
          resourcesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addResources(org.apache.mesos.Protos.Resource value) {
        if (resourcesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResourcesIsMutable();
          resources_.add(value);
          onChanged();
        } else {
          resourcesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addResources(
          int index, org.apache.mesos.Protos.Resource value) {
        if (resourcesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResourcesIsMutable();
          resources_.add(index, value);
          onChanged();
        } else {
          resourcesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addResources(
          org.apache.mesos.Protos.Resource.Builder builderForValue) {
        if (resourcesBuilder_ == null) {
          ensureResourcesIsMutable();
          resources_.add(builderForValue.build());
          onChanged();
        } else {
          resourcesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addResources(
          int index, org.apache.mesos.Protos.Resource.Builder builderForValue) {
        if (resourcesBuilder_ == null) {
          ensureResourcesIsMutable();
          resources_.add(index, builderForValue.build());
          onChanged();
        } else {
          resourcesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllResources(
          java.lang.Iterable<? extends org.apache.mesos.Protos.Resource> values) {
        if (resourcesBuilder_ == null) {
          ensureResourcesIsMutable();
          super.addAll(values, resources_);
          onChanged();
        } else {
          resourcesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearResources() {
        if (resourcesBuilder_ == null) {
          resources_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          resourcesBuilder_.clear();
        }
        return this;
      }
      public Builder removeResources(int index) {
        if (resourcesBuilder_ == null) {
          ensureResourcesIsMutable();
          resources_.remove(index);
          onChanged();
        } else {
          resourcesBuilder_.remove(index);
        }
        return this;
      }
      public org.apache.mesos.Protos.Resource.Builder getResourcesBuilder(
          int index) {
        return getResourcesFieldBuilder().getBuilder(index);
      }
      public org.apache.mesos.Protos.ResourceOrBuilder getResourcesOrBuilder(
          int index) {
        if (resourcesBuilder_ == null) {
          return resources_.get(index);  } else {
          return resourcesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.apache.mesos.Protos.ResourceOrBuilder> 
           getResourcesOrBuilderList() {
        if (resourcesBuilder_ != null) {
          return resourcesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(resources_);
        }
      }
      public org.apache.mesos.Protos.Resource.Builder addResourcesBuilder() {
        return getResourcesFieldBuilder().addBuilder(
            org.apache.mesos.Protos.Resource.getDefaultInstance());
      }
      public org.apache.mesos.Protos.Resource.Builder addResourcesBuilder(
          int index) {
        return getResourcesFieldBuilder().addBuilder(
            index, org.apache.mesos.Protos.Resource.getDefaultInstance());
      }
      public java.util.List<org.apache.mesos.Protos.Resource.Builder> 
           getResourcesBuilderList() {
        return getResourcesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.mesos.Protos.Resource, org.apache.mesos.Protos.Resource.Builder, org.apache.mesos.Protos.ResourceOrBuilder> 
          getResourcesFieldBuilder() {
        if (resourcesBuilder_ == null) {
          resourcesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.apache.mesos.Protos.Resource, org.apache.mesos.Protos.Resource.Builder, org.apache.mesos.Protos.ResourceOrBuilder>(
                  resources_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          resources_ = null;
        }
        return resourcesBuilder_;
      }
      
      // optional string description = 5;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000010);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        description_ = value;
        onChanged();
      }
      
      // optional uint32 port = 6;
      private int port_ ;
      public boolean hasPort() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getPort() {
        return port_;
      }
      public Builder setPort(int value) {
        bitField0_ |= 0x00000020;
        port_ = value;
        onChanged();
        return this;
      }
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000020);
        port_ = 0;
        onChanged();
        return this;
      }
      
      // optional double rackAffinity = 7;
      private double rackAffinity_ ;
      public boolean hasRackAffinity() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public double getRackAffinity() {
        return rackAffinity_;
      }
      public Builder setRackAffinity(double value) {
        bitField0_ |= 0x00000040;
        rackAffinity_ = value;
        onChanged();
        return this;
      }
      public Builder clearRackAffinity() {
        bitField0_ = (bitField0_ & ~0x00000040);
        rackAffinity_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double nodeAffinity = 8;
      private double nodeAffinity_ ;
      public boolean hasNodeAffinity() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public double getNodeAffinity() {
        return nodeAffinity_;
      }
      public Builder setNodeAffinity(double value) {
        bitField0_ |= 0x00000080;
        nodeAffinity_ = value;
        onChanged();
        return this;
      }
      public Builder clearNodeAffinity() {
        bitField0_ = (bitField0_ & ~0x00000080);
        nodeAffinity_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:mesosphere.marathon.ServiceDefinition)
    }
    
    static {
      defaultInstance = new ServiceDefinition(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:mesosphere.marathon.ServiceDefinition)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mesosphere_marathon_ServiceDefinition_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mesosphere_marathon_ServiceDefinition_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016marathon.proto\022\023mesosphere.marathon\032\013m" +
      "esos.proto\"\306\001\n\021ServiceDefinition\022\n\n\002id\030\001" +
      " \002(\t\022\037\n\003cmd\030\002 \002(\0132\022.mesos.CommandInfo\022\021\n" +
      "\tinstances\030\003 \002(\r\022\"\n\tresources\030\004 \003(\0132\017.me" +
      "sos.Resource\022\023\n\013description\030\005 \001(\t\022\014\n\004por" +
      "t\030\006 \001(\r\022\024\n\014rackAffinity\030\007 \001(\001\022\024\n\014nodeAff" +
      "inity\030\010 \001(\001B\035\n\023mesosphere.marathonB\006Prot" +
      "os"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_mesosphere_marathon_ServiceDefinition_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_mesosphere_marathon_ServiceDefinition_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mesosphere_marathon_ServiceDefinition_descriptor,
              new java.lang.String[] { "Id", "Cmd", "Instances", "Resources", "Description", "Port", "RackAffinity", "NodeAffinity", },
              mesosphere.marathon.Protos.ServiceDefinition.class,
              mesosphere.marathon.Protos.ServiceDefinition.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.apache.mesos.Protos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
