
get:
  description: Returns the list of all loaded plugins
  responses:
    200:
      description: The list of all loaded plugins
      body:
        application/json:
          example: |
            {
                "plugins": [
                    {
                        "id": "webjar",
                        "implementation": "mesosphere.marathon.example.plugin.http.WebJarHandler",
                        "info": {
                            "version": "1.2.3",
                            "array": [ 1, 2, 3, 4, 5, 6 ],
                            "test": true
                        },
                        "plugin": "mesosphere.marathon.plugin.http.HttpRequestHandler",
                        "tags": [ "webjar", "test" ]
                    }
                ]
            }

/{plugin_id}/{path}:
  get:
    description: Get request is handled by the plugin.
  put:
    description: Put request is handled by the plugin.
  post:
    description: Post request is handled by the plugin.
  delete:
    description: Delete request is handled by the plugin.
