package mesosphere.mesos

object TaskBuilderConstants {
  val MARATHON_APP_ENFORCE_GROUP_ROLE = "MARATHON_APP_ENFORCE_GROUP_ROLE"
  val MESOS_EXECUTOR_ID = "MESOS_EXECUTOR_ID"
  val MESOS_TASK_ID = "MESOS_TASK_ID"
  val MARATHON_APP_ID = "MARATHON_APP_ID"
  val MARATHON_APP_VERSION = "MARATHON_APP_VERSION"
  val MARATHON_CONTAINER_ID = "MARATHON_CONTAINER_ID"
  val MARATHON_CONTAINER_RESOURCE_CPUS = "MARATHON_CONTAINER_RESOURCE_CPUS"
  val MARATHON_CONTAINER_RESOURCE_MEM = "MARATHON_CONTAINER_RESOURCE_MEM"
  val MARATHON_CONTAINER_RESOURCE_DISK = "MARATHON_CONTAINER_RESOURCE_DISK"
  val MARATHON_CONTAINER_RESOURCE_GPUS = "MARATHON_CONTAINER_RESOURCE_GPUS"

  val MARATHON_APP_DOCKER_IMAGE = "MARATHON_APP_DOCKER_IMAGE"
  val MARATHON_APP_RESOURCE_CPUS = "MARATHON_APP_RESOURCE_CPUS"
  val MARATHON_APP_RESOURCE_MEM = "MARATHON_APP_RESOURCE_MEM"
  val MARATHON_APP_RESOURCE_DISK = "MARATHON_APP_RESOURCE_DISK"
  val MARATHON_APP_RESOURCE_GPUS = "MARATHON_APP_RESOURCE_GPUS"
}
