#%RAML 1.0 Library

types:
  TTY:
    type: object
    description: |
      Describes the information about (pseudo) TTY that can be attached to a process running in a container.
    properties:
      rows?:
        type: integer
        description: The rows of the tty device.
        minimum: 1
        format: int32
        default: 25
      columns?:
        type: integer
        description: The columns of the tty device.
        minimum: 1
        format: int32
        default: 80
