#%RAML 1.0 Library
usage: |
  Defines Status for Containers
uses:
  strings: stringTypes.raml
  a: ../../annotations.raml
  numbers: numberTypes.raml
  statusCondition: statusCondition.raml
types:
  ContainerState:
    type: string
    usage: |
      TODO(jdef) This should be an enum and we should have an externally visible type for it
    description: |
      Reflects the status of the associated Mesos task.
  ContainerEndpointStatus:
    type: object
    properties:
      name:
        type: strings.Name
        description: name of the endpoint
      allocatedHostPort?: numbers.Port
      healthy?:
        type: boolean
        usage: should only be present if a health check is defined for this endpoint
        description: true if a health check is defined for this endpoint and is passing
  ContainerTerminationState:
    type: object
    properties:
      exitCode?:
        type: integer
        format: int32
      message?:
        type: string
        description: Human-explanation for container termination.
  ContainerStatus:
    type: object
    properties:
      name:
        type: strings.Name
        description: name of the container specification (within the pod)
      status: ContainerState
      statusSince:
        type: datetime
        description: |
          Time at which the status code was last modified.
      message?:
        type: string
        description: |
          Human-friendly explanation for the container's current status.
      conditions?:
        type: array
        description: |
          Set of status conditions that apply to this container.
        items: statusCondition.StatusCondition
      containerId?:
        type: string
        description: |
          Unique ID of this container in the cluster.
          TODO(jdef) Probably represents the Mesos task ID.
      endpoints?:
        type: array
        items: ContainerEndpointStatus
      termination?: ContainerTerminationState
      lastUpdated:
        type: datetime
        description: |
          Time that this status was last checked and updated (even if nothing changed)
      lastChanged:
        type: datetime
        description: |
          Time that this status was last modified (some aspect of status did change)
  ContainerStatuses:
    type: array
    items: ContainerStatus
