#%RAML 1.0 DataType
type: object
additionalProperties: false
properties:
  name:
    type: !include name.raml
    description: name of the container specification (within the pod)
  status:
    type: string
    usage: |
      TODO(jdef) this is not an enum because it reflects Marathon internal state that
      could easily change going forward and I don't want breaking API changes that result
      from a shifting enum here.
    description: |
      Reflects the status of the associated Mesos task.
  statusSince:
    type: datetime
    description: |
      Time at which the status code was last modified.
  message?:
    type: string
    description: |
      Human-friendly explanation for the container's current status.
  conditions?:
    type: array
    description: |
      Set of status conditions that apply to this container.
    items:
      type: !include status-condition.raml
  containerId?:
    type: string
    description: |
      Unique ID of this container in the cluster.
      TODO(jdef) Probably represents the Mesos task ID.
  endpoints?:
    type: array
    items:
      type: object
      additionalProperties: false
      properties:
        name:
          type: !include name.raml
          description: name of the endpoint
        allocatedHostPort?:
          type: !include port.raml
        healthy?:
          type: boolean
          usage: should only be present if a health check is defined for this endpoint
          description: true if a health check is defined for this endpoint and is passing
  termination?:
    type: object
    additionalProperies: false
    properties:
      exitCode?:
        type: integer
      message?:
        type: string
        description: Human-explanation for container termination.
  lastUpdated:
    type: datetime
    description: |
      Time that this status was last checked and updated (even if nothing changed)
  lastChanged:
    type: datetime
    description: |
      Time that this status was last modified (some aspect of status did change)
