#%RAML 1.0 Library
uses:
  strings: stringTypes.raml
  deploymentAction: deploymentAction.raml
  pragma: pragma.raml

types:
  DeploymentSteps:
    type: object
    (pragma.serializeOnly): # Used only for serialization
    properties:
      steps:
        type: array
        items: DeploymentStep

  DeploymentStep:
    type: object
    (pragma.serializeOnly): # Used only for serialization
    description: |
      A step in the deployment plan, represented as a list of actions to be performed
    properties:
      actions:
        type: array
        items: deploymentAction.DeploymentAction
