#%RAML 1.0 DataType
type: object
usage: Must specify a single type of check, http, tcp, or command
maxProperties: 1
minProperties: 1
properties:
  http?:
    type: object
    properties:
      endpoint:
        type: !include name.raml
        description: |
          The endpoint name to use.
          In "host" mode health checks use the hostPort. In other modes use the containerPort.
      path?:
        type: string
        minLength: 1
        maxLength: 1024
      scheme?:
        type: string
        enum: [ HTTP, HTTPS ]
        description: The http scheme to use
  tcp?:
    type: object
    properties:
      endpoint:
        type: !include name.raml
        description: |
          The endpoint name to use.
          In "host" mode health checks use the hostPort. In other modes use the containerPort.
  command?:
    type: !include mesosCommand.raml
