#%RAML 1.0 Library
uses:
  strings: stringTypes.raml
  command: mesosCommand.raml
types:
  HttpHealthCheck:
    type: object
    properties:
      endpoint:
        type: strings.Name
        description: |
          The endpoint name to use.
          In "host" mode health checks use the hostPort. In other modes use the containerPort.
      path?: strings.Path
      scheme?: strings.HttpScheme
      /^tcp$/:
      /^command$/:
  TcpHealthCheck:
    type: object
    properties:
      endpoint:
        type: strings.Name
        description: |
          The endpoint name to use.
          In "host" mode health checks use the hostPort. In other modes use the containerPort.
      /^http$/:
      /^command$/:
  CommandHealthCheck:
    type: object
    properties:
      command: command.MesosCommand
      /^http$/:
      /^tcp$/:
  HealthCheck:
    type: (HttpHealthCheck | TcpHealthCheck | CommandHealthCheck)
    usage: Must specify a single type of check, http, tcp, or command
