#%RAML 1.0 Library
uses:
  strings: stringTypes.raml
types:
  ImageType:
    type: string
    enum: [DOCKER, APPC]
  Image:
    type: object
    properties:
      kind: ImageType
      id:
        type: strings.Path
        description: address/identifier of the file system image
        example: mesosphere/marathon:1.3.0
      forcePull?:
        type: boolean
        description: true if the image should always be pulled
