#%RAML 1.0 Library
uses:
  health: healthCheck.raml
  numbers: numberTypes.raml
  strings: stringTypes.raml
  offer: offer.raml
  task: task.raml
  unreachableStrategy: unreachableStrategy.raml

types:

  AgentInfo:
    type: object
    properties:
      host: string
      agentId?: string
      region?: string
      zone?: string
      attributes: offer.AgentAttribute[]

  InstanceState:
    type: object
    properties:
      condition: strings.Condition
      since: datetime
      activeSince?: datetime
      healthy?: boolean

  Instance_Id:
    type: object
    properties:
      idString: strings.InstanceId

  Instance:
    type: object
    properties:
      instanceId: Instance_Id
      agentInfo: AgentInfo
      tasksMap:
        type: object
        properties:
          /.*/: task.Task
      runSpecVersion: datetime
      state: InstanceState
      unreachableStrategy: unreachableStrategy.UnreachableStrategy

  InstanceList:
    type: object
    properties:
      tasks: Instance[]
    