#%RAML 1.0 Library
uses:
  offer: offer.raml
  strings: stringTypes.raml
  task: task.raml
  unreachableStrategy: unreachableStrategy.raml

types:
  AgentInfo:
    type: object
    properties:
      host: string
      agentId?: string
      region?: string
      zone?: string
      attributes: offer.AgentAttribute[]
  InstanceId:
    type: object
    properties:
      idString: strings.InstanceId
  InstanceState:
    type: object
    properties:
      condition: strings.Condition
      since: datetime
      activeSince?: datetime
      healthy?: boolean
  TaskMap:
    type: object
    properties:
      /^.*$/: task.Task
  Instance:
    type: object
    properties:
      instanceId: InstanceId
      state: InstanceState
      agentInfo?: AgentInfo
      tasksMap: TaskMap
      runSpecVersion: datetime
      unreachableStrategy: unreachableStrategy.UnreachableStrategy
