#%RAML 1.0 Library
uses:
  strings: stringTypes.raml

types:
  Seccomp:
    type: object
    properties:
      profileName?:
        type: string
        description: Filename of the Seccomp profile found on the agent.  The task will fail if that file does not exist.
      unconfined:
        type: boolean
        description:  Set to `true` if Seccomp is not applied to the container
        default: false
  IPCMode:
    type: string
    enum: [PRIVATE, SHARE_PARENT]
  IPCInfo:
    type: object
    properties:
      mode:
        type: IPCMode
        description: Defines the shared memory and IPC contraints.
      shmSize?:
        type: number
        format: int32
        description: The size of shared memory to be used in MiB.
  LinuxInfo:
    type: object
    properties:
      seccomp?: Seccomp
      ipcInfo?: IPCInfo
