#%RAML 1.0 Library
uses:
  artifacts: artifact.raml
  endpoint: endpoint.raml
  env: environmentVariable.raml
  health: healthCheck.raml
  image: image.raml
  labels: label.raml
  mesosCommand: mesosCommand.raml
  resources: resources.raml
  strings: stringTypes.raml
  volumes: volumes.raml
types:
  MesosContainer:
    type: object
    description: Mesos Container
    properties:
      name:
        type: strings.Name
        description: The name of this container
      exec?:
        type: object
        properties:
          command:
            type: mesosCommand.MesosCommand
            description: |
              Command specification executed by Mesos, not parsed by Marathon.
              The presence of `command.shell` implies `overrideEntrypoint=true`.
          overrideEntrypoint?:
            type: boolean
            usage: |
              Applies only if a container image is specified AND that container image
              defines a default entrypoint (Docker) or exec (appc) property.
              It is an error to use `false` here when `command.shell` is set.
            description: |
              When true argv[0] will be used as the entrypoint/exec of the container.
              Otherwise the contents of argv[] are appended as arguments.
      resources:
        type: resources.Resources
        description: The resources to allocate to the container.
      endpoints?:
        type: endpoint.Endpoints
        description: The ports needed to run this container
      image?:
        type: image.Image
        description: The filesystem image to populate the container with
      environment?: env.EnvVars
      user?:
        type: string
        description: |
          The OS user to use to run the tasks on the agent.
          Values here override a "user" value specified in the pod definition.
      healthCheck?:
        type: health.HealthCheck
        description: All healthchecks to perform on the container
      volumeMounts?:
        type: volumes.VolumeMounts
        description: All volume mounts
      artifacts?:
        type: artifacts.Artifacts
        description:
          All artifacts to download before the task runs
      labels?:
        type: labels.Labels
        description: |
          Metadata as key/value pair.
          Useful when passing directives to be interpreted by Mesos modules.
  MesosContainers:
    type: array
    items: MesosContainer
