#%RAML 1.0 DataType
type: object
(scalaType): Network
properties:
  name?:
    type: !include name.raml
    description: |
      Defines the name of the container network to join.
      Not for use with `host` mode networking
  mode?:
    type: string
    (scalaType): NetworkMode
    enum: [container, host]
  labels?:
    type: array
    items: !include label.raml
