#%RAML 1.0 Library
uses:
  label: label.raml
  strings: stringTypes.raml
types:
  NetworkMode:
    type: string
    enum: [container, host]
  Network:
    type: object
    properties:
      name?:
        type: strings.Name
        description: |
          Defines the name of the container network to join.
          Not for use with `host` mode networking
      mode?: NetworkMode
      labels?: label.Labels
  Networks:
    type: array
    items: Network
