#%RAML 1.0 Library
types:
  NewCounter:
    type: object
    properties:
      count:
        type: integer
        format: int64
  NewGauge:
    type: object
    properties:
      value:
        type: number
        format: double
  NewHistogram:
    type: object
    properties:
      count:
        type: integer
        format: int64
      min:
        type: number
        format: double
      mean:
        type: number
        format: double
      max:
        type: number
        format: double
      p50:
        type: number
        format: double
      p75:
        type: number
        format: double
      p95:
        type: number
        format: double
      p98:
        type: number
        format: double
      p99:
        type: number
        format: double
      p999:
        type: number
        format: double
      stddev:
        type: number
        format: double
  NewMeter:
    type: object
    properties:
      count:
        type: integer
        format: int64
      m1_rate:
        type: number
        format: double
      m5_rate:
        type: number
        format: double
      m15_rate:
        type: number
        format: double
      mean_rate:
        type: number
        format: double
      units: string
  NewTimer:
    type: object
    properties:
      count:
        type: integer
        format: int64
      min:
        type: number
        format: double
      mean:
        type: number
        format: double
      max:
        type: number
        format: double
      p50:
        type: number
        format: double
      p75:
        type: number
        format: double
      p95:
        type: number
        format: double
      p98:
        type: number
        format: double
      p99:
        type: number
        format: double
      p999:
        type: number
        format: double
      stddev:
        type: number
        format: double
      m1_rate:
        type: number
        format: double
      m5_rate:
        type: number
        format: double
      m15_rate:
        type: number
        format: double
      mean_rate:
        type: number
        format: double
      duration_units: string
      rate_units: string
  NewMetrics:
    type: object
    properties:
      version: string
      counters:
        type: object
        properties:
          /.*/: NewCounter
      gauges:
        type: object
        properties:
          /.*/: NewGauge
      histograms:
        type: object
        properties:
          /.*/: NewHistogram
      meters:
        type: object
        properties:
          /.*/: NewMeter
      timers:
        type: object
        properties:
          /.*/: NewTimer
