#%RAML 1.0 Library
types:
  PluginDefinition:
    type: object
    properties:
      id: string
      plugin: string
      implementation: string
      tags?: string[]
      info: object
  PluginDefinitions:
    type: object
    properties:
      plugins: PluginDefinition[]
