#%RAML 1.0 DataType
type: object
additionalProperties: false
properties:
  id:
    type: !include name.raml
    description: |
      Unique ID of this pod instance in the cluster.
      TODO(jdef) Probably represents the Mesos executor ID.
  status:
    type: string
    usage: |
      TODO(jdef) this is not an enum because it reflects Marathon internal state that
      could easily change going forward and I don't want breaking API changes that result
      from a shifting enum here.
    description: |
      Reflects the aggregate status of all containers for this pod instance.
      For example RESERVED, CREATED, STAGING, STARTING, RUNNING, ERROR, FAILED, KILLING.
  statusSince:
    type: datetime
    description: |
      Time at which the status code was last modified.
  message?:
    type: string
    description: |
      Human-friendly explanation for reason of the current status.
  conditions?:
    type: array
    description: |
      Set of status conditions that apply to this pod instance.
    items:
      type: !include status-condition.raml
  agent?:
    type: string
    description: agent that this instance was launched on
  resources?:
    type: !include resources.raml
    description: |
      Sum of all resources allocated for this pod instance.
      May include additional, system-allocated resources for the default executor.
  networks?:
    type: array
    description: |
      Status of the networks to which this instance is attached.
    items:
      type: object
      additionalProperties: false
      properties:
        name?:
          type: !include name.raml
          description: name of the network
        addresses?:
          type: string[]
  containers?:
    type: array
    description: status for each running container of this instance.
    items:
      type: !include container-status.raml
  lastUpdated:
    type: datetime
    description: |
      Time that this status was last checked and updated (even if nothing changed)
  lastChanged:
    type: datetime
    description: |
      Time that this status was last modified (some aspect of status did change)
