#%RAML 1.0 DataType
(scalaType): PortDefinition
type: object
additionalProperties: false
properties:
  port?:
    type: integer
    format: int32
    description: |
      if requirePorts is set to true, then this port number will be used
      on the agent host Otherwise if the requirePorts is set to false and
      this port number is not zero, then it will be used as a service port
      and a dynamic port will be used on the agent host.
      If it is set to zero, a dynamic port will be used on the host and a
      unique service port will be assigned by Marathon.
  labels?: !include label.raml
  name?:
    type: string
    description: |
      Name of the service hosted on this port.
      If provided, it must be unique over all port definitions.
    pattern: ^[a-z][a-z0-90]*$
  protocol?: !include networkProtocol.raml
