#%RAML 1.0 Library
types:
  SecretDef:
    type: object
    description: A secret declaration
    properties:
      source:
        type: string
        description: |
          The source of the secrets value.
          The format dependes on the secret store
        minLength: 1
  Secrets:
    type: object
    description: |
      A map with named secret declarations.
      The key is used to reference the values from other places in the parent definition.
    properties:
      /.*/: SecretDef
