#%RAML 1.0 DataType
type: object
additionalProperties: false
properties:
  name:
    type: !include name.raml
    description: |
      Human and machine-readable name of this condition.
      For example "healthy", "disk-full".
  lastChanged:
    type: datetime
    description: last time the value field was changed for this condition
  lastUpdated:
    type: datetime
    description: last time this condition was updated (value may not have changed)
  value:
    type: string
    description: the state of the condition. may be boolean or some enumeration-derived value
    maxLength: 64
  reason?:
    type: string
    description: |
      a machine-readable value that systems use to reason about the state of the condition
