#%RAML 1.0 Library
types:
  UnreachableStrategy: (UnreachableDisabled | UnreachableEnabled)
  UnreachableDisabled:
    type: string
    enum: [ disabled ]
    default: disabled
  UnreachableEnabled:
    type: object
    properties:
      inactiveAfterSeconds?:
        type: integer
        format: int64
        default: 300
        minimum: 1
        description: |
          If an instance is unreachable for longer than inactiveAfter seconds it is marked
          as inactive. This will trigger a new instance launch. The original task is not
          expunged yet. Must be less than expungeAfterSeconds.

          The default value is set to 5 minutes (300 seconds).

      expungeAfterSeconds?:
        type: integer
        format: int64
        default: 600
        minimum: 1
        description: |
          If an instance is unreachable for longer than unreachableExpungeAfter seconds it will be expunged.  That means
          it will be killed if it ever comes back. Instances are usually marked as unreachable before they are expunged
          but they don't have to. This value is required to be greater than inactiveAfterSeconds.

          The default value is set to 10 minutes (600 seconds).
