#%RAML 1.0 Library
types:
  UnreachableStrategy:
    type: object
    properties:
      inactiveAfterSeconds?:
        type: integer
        format: int64
        default: 900
        minimum: 1
        description: |
          If an instance is unreachable for longer than inactiveAfter seconds it is marked
          as inactive. This will trigger a new instance launch. The original task is not
          expunged yet. Must be less than expungeAfterSeconds.
      expungeAfterSeconds?:
        type: integer
        format: int64
        default: 604800
        minimum: 1
        description: |
          If an instance is unreachable for longer than unreachableExpungeAfter seconds it will be expunged.  That means
          it will be killed if it ever comes back. Instances are usually marked as unreachable before they are expunged
          but they don't have to. This value is required to be greater than inactiveAfterSeconds.

          If the instance has any persistent volumes associated with it, then they will be destroyed and associated data
          will be deleted.

          Default is 7 days (604800 seconds).
