#%RAML 1.0 Library
types:
  UnreachableStrategy: (UnreachableDisabled | UnreachableEnabled)
  UnreachableDisabled:
    type: string
    enum: [ disabled ]
    default: disabled
  UnreachableEnabled:
    type: object
    properties:
      inactiveAfterSeconds?:
        type: integer
        format: int64
        default: 0
        minimum: 0
        description: |
          If an instance is unreachable for longer than inactiveAfter seconds it is marked
          as inactive. This will trigger a new instance launch. The original task is not
          expunged yet. Must be less than or equal to expungeAfterSeconds.

          The default value is set to 0 seconds.

      expungeAfterSeconds?:
        type: integer
        format: int64
        default: 0
        minimum: 0
        description: |
          If an instance is unreachable for longer than expungeAfterSeconds it will be expunged.  That means
          it will be killed if it ever comes back. Instances are usually marked as unreachable before they are expunged
          but they don't have to. This value is required to be greater than or equal to inactiveAfterSeconds.

          The default value is set to 0 seconds.
