#%RAML 1.0 DataType
type: object
properties:
  name:
    type: !include name.raml
    description: The name of the volume to reference.
  host?:
    type: string
    description: |
      Absolute path of the file or directory on the agent, or else the relative
      path of the directory in the executor's sandbox.
      Host volumes are useful for mapping directories that exist on the agent apriori,
      or within the executor sandbox. No resources (Mesos or otherwise) are allocated for
      these types of volumes.
